CREATE TABLE  `DB_HOMECARE`.`TBL_PERSONAS` (
  `PERS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PERS_IDENTIFICACION` varchar(45) NOT NULL,
  `PERS_LUGAREXPEDICION` varchar(200) DEFAULT NULL,
  `PERS_FECHAEXPEDICION` date NULL,
  `PERS_PRIMERNOMBRE` varchar(45) NOT NULL,
  `PERS_SEGUNDONOMBRE` varchar(45) DEFAULT NULL,
  `PERS_PRIMERAPELLIDO` varchar(45) NOT NULL,
  `PERS_SEGUNDOAPELLIDO` varchar(45) DEFAULT NULL,
  `PERS_FECHANACIMIENTO` date NOT NULL,
  `PERS_LUGARNACIMIENTO` varchar(200) DEFAULT NULL,
  `PERS_DIRECCION` varchar(200) DEFAULT NULL,
  `PERS_TELEFONOFIJO` varchar(200) DEFAULT NULL,
  `PERS_TELEFONOMOVIL` varchar(200) DEFAULT NULL,
  `PERS_SENDSMS` tinyint(1) DEFAULT '0',
  `PERS_EMAIL` text,
  `PERS_SENDMAIL` tinyint(1) DEFAULT '0',
  `PERS_PATHIMG` text,
  `PERS_CUALOTRAEPS` varchar(200) DEFAULT NULL,
  `EPSS_ID` int(11) NOT NULL,
  `ESTR_ID` int(11) DEFAULT NULL,
  `NIES_ID` int(11) DEFAULT NULL,
  `ESCI_ID` int(11) DEFAULT NULL,
  `TIID_ID` int(11) NOT NULL,
  `TIGE_ID` int(11) NOT NULL,
  `PAIS_ID` int(11) DEFAULT NULL,
  `DEPA_ID` int(11) DEFAULT NULL,
  `MUNI_ID` int(11) DEFAULT NULL,
  `PERS_CREATEBY` int(11) NOT NULL,
  `PERS_UPDATEAT` timestamp NULL,
  PRIMARY KEY (`PERS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=latin1;

ALTER TABLE `TBL_PERSONAS` ADD COLUMN `PERS_LUGAREXPEDICION` VARCHAR(100) NULL AFTER `PERS_IDENTIFICACION`;
ALTER TABLE `TBL_PERSONAS` ADD COLUMN `PERS_FECHAEXPEDICION` date NULL AFTER `PERS_LUGAREXPEDICION`;
ALTER TABLE `TBL_PERSONAS` ADD COLUMN `PERS_TELEFONOMOVIL` VARCHAR(50) NULL AFTER `PERS_TELEFONO`;
ALTER TABLE `TBL_PERSONAS` ADD COLUMN `PERS_CUALOTRAEPS` VARCHAR(50) AFTER `PERS_PATHIMG`;
ALTER TABLE `TBL_PERSONAS` ADD COLUMN `EPSS_ID` INTEGER NOT NULL AFTER `PERS_CUALOTRAEPS`;
ALTER TABLE `TBL_PERSONAS` ADD COLUMN `ESTR_ID` INTEGER NOT NULL AFTER `EPSS_ID`;
ALTER TABLE `TBL_PERSONAS` ADD COLUMN `NIES_ID` INTEGER NOT NULL AFTER `ESTR_ID`;
ALTER TABLE `TBL_PERSONAS` ADD COLUMN `PERS_BARRIO` VARCHAR(50) NULL AFTER `PERS_DIRECCION`;
ALTER TABLE `TBL_PERSONAS` ADD COLUMN `ZONA_ID` INTEGER NOT NULL AFTER `PERS_BARRIO`;


CREATE TABLE  TBL_EPSS (
  `EPSS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EPSS_NOMBRE` varchar(50) NOT NULL,
  `EPSS_CODIGO` varchar(10) NOT NULL,
  `EPSS_DIRECCION` varchar(50) DEFAULT NULL,
  `EPSS_TELEFONO` varchar(50) DEFAULT NULL,
  `EPSS_CREATEBY` int(11) NOT NULL,
  `EPSS_UPDATEAT` timestamp NULL,
  PRIMARY KEY (`EPSS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE  TBL_ESTRACTOS (
  `ESTR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ESTR_NOMBRE` varchar(50) NOT NULL,
  `ESTR_CREATEBY` int(11) NOT NULL,
  `ESTR_UPDATEAT` timestamp NULL,
  PRIMARY KEY (`ESTR_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE  TBL_NIVELSESTUDIOS (
  `NIES_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NIES_NOMBRE` varchar(50) NOT NULL,
  `NIES_CREATEBY` int(11) NOT NULL,
  `NIES_UPDATEAT` timestamp NULL,
  PRIMARY KEY (`NIES_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE  TBL_ZONAS (
  `ZONA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ZONA_NOMBRE` varchar(50) NOT NULL,
  `ZONA_DESCRIPCION` varchar(50) NOT NULL,
  `ZONA_CREATEBY` int(11) NOT NULL,
  `ZONA_UPDATEAT` timestamp NULL,
  PRIMARY KEY (`ZONA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


CREATE TABLE  `DB_HOMECARE`.`TBL_BENEFICIARIOS` (
  `BENE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BENE_FECHAINGRESO` datetime DEFAULT NULL,
  `PERS_ID` int(11) NOT NULL,
  `AFIL_ID` int(11) NOT NULL,
  `PARE_ID` int(11) NOT NULL COMMENT 'PARENTESCO',
  `BENE_CREATEBY` int(11) NOT NULL,
  `BENE_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`BENE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

CREATE TABLE  `TBL_FORMASPAGOS` (
  `FOPA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FOPA_NUMEROCUENTA` varchar(50) COLLATE utf8_polish_ci DEFAULT NULL,
  `FOPA_NUMEROSEGURIDAD` int(11) DEFAULT NULL,
  `FOPA_FECHAVENCIMIENTO` date DEFAULT NULL,
  `FOPA_ACTUAL` boolean NOT NULL COMMENT 'Actual',
  `BANC_ID` int(11) NULL COMMENT 'BANCOS',
  `TICU_ID` int(11) NULL COMMENT 'TIPOS DE CUENTAS',
  `PEPA_ID` int(11) NOT NULL COMMENT 'PERIOCIDAD PAGOS',
  `AFIL_ID` int(11) NOT NULL COMMENT 'AFILIADOS',
  `FOPA_CREATEBY` int(11) NULL,
  `FOMA_UPDATEAT` timestamp NULL,
  PRIMARY KEY (`FOPA_ID`),
  KEY `AFIL_ID` (`AFIL_ID`),
  KEY `TICU_ID` (`TICU_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_polish_ci COMMENT='FORMAS PAGOS';

CREATE TABLE  TBL_TIPOSCUENTAS (
  `TICU_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TICU_NOMBRE` varchar(50) NOT NULL,
  `TICU_CREATEBY` int(11) NULL,
  `TICU_UPDATEAT` timestamp NULL,
  PRIMARY KEY (`TICU_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE  TBL_PERIOCIDADPAGOS (
  `PEPA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PEPA_NOMBRE` varchar(50) NOT NULL,
  `PEPA_CREATEBY` int(11) NULL,
  `PEPA_UPDATEAT` timestamp NULL,
  PRIMARY KEY (`PEPA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

ALTER TABLE `TBL_AGENDA` ADD COLUMN `AGEN_TOKEN` TEXT NOT NULL AFTER `AGEN_ID`,
 DROP PRIMARY KEY,
 ADD PRIMARY KEY  USING BTREE(`AGEN_ID`);
 
 
DROP TABLE IF EXISTS `TBL_PAGOS`;
CREATE TABLE  `TBL_PAGOS` (
  `PAGO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PAGO_FECHA` datetime NOT NULL,
  `PAGO_FECHAINICIO` date NOT NULL,
  `PAGO_FECHAFINAL` date NOT NULL,
  `PAGO_VALOR` double NOT NULL,
  `ESPA_ID` int(11) NOT NULL,
  `AFIL_ID` int(11) NOT NULL,
  `PAGO_CREATEBY` int(11) NOT NULL,
  `PAGO_UPDATEAT` timestamp NULL,
  PRIMARY KEY (`PAGO_ID`),
  KEY `AFIL_ID` (`AFIL_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='PAGOS';

CREATE TABLE  `TBL_PLANES` (
  `PLAN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PLAN_NOMBRE` varchar(200) NOT NULL,
  `PLAN_DESCRIPCION` varchar(200) NULL,
  `PLAN_VALORMENSUAL` double NOT NULL,
  `PLAN_VALORSEMESTRAL` double NULL,
  `PLAN_VALORANUAL` double NULL,
  `PLAN_CREATEBY` int(11) NOT NULL,
  `PLAN_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PLAN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='PLANES';

3005467693

ALTER TABLE `TBL_AFILIADOS` ADD COLUMN `PLAN_ID` INTEGER NOT NULL AFTER `PERS_ID`;

CREATE TABLE  `TBL_ESTADOSPAGOS` (
  `ESPA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ESPA_NOMBRE` varchar(50) NOT NULL,
  `ESPA_CREATEBY` int(11) NOT NULL,
  `ESPA_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ESPA_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


CREATE TABLE  `TBL_AGENDA` (
  `AGEN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AGEN_FECHAPROCESO` DATETIME NOT NULL,
  `AGEN_FECHA` DATETIME NOT NULL,
  `AGEN_HORAINICIO` TIME NOT NULL,
  `AGEN_HORAFINAL` TIME NOT NULL,
  `FINA_ID` int(11) NOT NULL COMMENT 'FINALIDADES',
  `PERS_ID` int(11) NOT NULL COMMENT 'PERSONAS',
  `PEEM_ID` int(11) NOT NULL COMMENT 'MEDICOS',
  `ESTA_ID` int(11) NOT NULL COMMENT 'ESTADOS',
  `AGEN_CREATEBY` int(11) NOT NULL,
  `AGEN_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`AGEN_ID`),
  KEY `PERS_ID` (`PERS_ID`),
  KEY `FINA_ID` (`FINA_ID`),
  KEY `PEEM_ID` (`PEEM_ID`),
  KEY `ESTA_ID` (`ESTA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf32 COLLATE=utf32_spanish_ci COMMENT='AGENDA';




CREATE TABLE  `TBL_CAUSASEXTERNAS` (
  `CAEX_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CAEX_NOMBRE` varchar(50) COLLATE utf8_spanish_ci NOT NULL,
  `CAEX_CODIGO` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `CAEX_CREATEBY` int(11) NOT NULL,
  `CAEX_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CAEX_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='CAUSAS EXTERNAS';


///////////////////////////////////////////////////////////////////
CREATE TABLE  `TBL_ATNGENERALIDADES` (
  `ATGE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATGE_FECHA` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ATGE_MOTIVO` text COLLATE utf32_spanish_ci,
  `ATGE_ENFERMEDAD` text COLLATE utf32_spanish_ci,
  `CAEX_ID` int(11) NOT NULL COMMENT 'CAUSA EXTERNA',
  `AGEN_ID` int(11) NOT NULL COMMENT 'AGENDA',
  `ATGE_CREATEBY` int(11) NOT NULL,
  `ATGE_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ATGE_ID`),
  KEY `AGEN_ID` (`AGEN_ID`),
  KEY `CAEX_ID` (`CAEX_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf32 COLLATE=utf32_spanish_ci COMMENT='GENERALIDADES';

CREATE TABLE  `TBL_ATNANTECEDENTESPERSONALES` (
  `ATAP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATAP_HIPERTENSION` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAP_DIABETES` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAP_ENETOMBOTICA` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAP_CONVULSIONES` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAP_VALVULOPATIAS` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAP_HEPATICA` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAP_CEFALEA` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAP_MAMARIA` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAP_OTROS` text NULL,
  `PERS_ID` int(11) NOT NULL COMMENT 'PERSONA',
  `ATAP_CREATEBY` int(11) NOT NULL,
  `ATAP_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ATAP_ID`),
  KEY `PERS_ID` (`PERS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ANTECEDENTES PERSONALES';

CREATE TABLE  `TBL_ATNANTECEDENTESFAMILIARES` (
  `ATAF_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATAF_HIPERTENSION` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAF_DIABETES` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAF_CONVULSIVO` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAF_MALFORMACIONES` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAF_CANCER` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAF_OTROS` text NULL,
  `PERS_ID` int(11) NOT NULL COMMENT 'PERSONA',
  `ATAF_CREATEBY` int(11) NOT NULL,
  `ATAF_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ATAF_ID`),
  KEY `PERS_ID` (`PERS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ANTECEDENTES FAMILIARES';

CREATE TABLE  `TBL_ATNHABITOS` (
  `ATHA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATHA_ALCOHOL` varchar(2) COLLATE utf8_spanish_ci NOT NULL DEFAULT 'NO',
  `ATHA_CIGARRILLO` varchar(2) COLLATE utf8_spanish_ci NOT NULL DEFAULT 'NO',
  `ATHA_DROGAS` varchar(2) COLLATE utf8_spanish_ci NOT NULL DEFAULT 'NO',
  `ATHA_OTROS` text COLLATE utf8_spanish_ci,
  `PERS_ID` int(11) NOT NULL,
  `ATHA_CREATEBY` int(11) NOT NULL,
  `ATHA_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ATHA_ID`),
  KEY `PERS_ID` (`PERS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='HABITOS';

CREATE TABLE IF NOT EXISTS `TBL_ATNREVISIONSISTEMAS` (
  `ATRS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATRS_GENERAL` text NOT NULL,
  `ATRS_RESPIRATORIO` text NOT NULL,
  `ATRS_CARDIOVASCULAR` text NOT NULL,
  `ATRS_GASTROINTESTINAL` text NOT NULL,
  `ATRS_GENITOURINARIO` text NOT NULL,
  `ATRS_ENDOCRINO` text NOT NULL,
  `ATRS_NEUROLOGICO` text NOT NULL,
  `AGEN_ID` int(11) NOT NULL,
  `ATRS_CREATEBY` int(11) NOT NULL,
  `ATRS_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ATRS_ID`),
  KEY `AGEN_ID` (`AGEN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='REVISION SISTEMAS';

CREATE TABLE IF NOT EXISTS `TBL_ATNSIGNOSVITALES` (
  `ATSV_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATSV_PRESIONHH` varchar(20) NOT NULL DEFAULT '0',
  `ATSV_PRESIONMM` varchar(20) NOT NULL DEFAULT '0',
  `ATSV_PESO` varchar(20) NOT NULL DEFAULT '0',
  `ATSV_TALLA` varchar(20) NOT NULL DEFAULT '0',
  `ATSV_IMC` varchar(20) NOT NULL DEFAULT '0',
  `ATSV_FRECUENCIAC` varchar(20) NOT NULL DEFAULT '0',
  `ATSV_FRECUENCIAR` varchar(20) NOT NULL DEFAULT '0',
  `ATSV_PERIMETROA` varchar(20) NOT NULL DEFAULT '0',
  `ATSV_PERIMETROC` varchar(20) NOT NULL DEFAULT '0',
  `ATSV_PERIMETROB` varchar(20) NOT NULL DEFAULT '0',
  `ATSV_TEMPERATURA` varchar(20) NOT NULL DEFAULT '0',
  `AGEN_ID` int(11) NOT NULL,
  `ATSV_CREATEBY` int(11) NOT NULL,
  `ATSV_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ATSV_ID`),
  KEY `AGEN_ID` (`AGEN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='SIGNOS VITALES';

CREATE TABLE IF NOT EXISTS `TBL_ATNEXAMENFISICO` (
  `ATEF_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATEF_ASPECTO` text NOT NULL,
  `ATEF_ESTADO` text NOT NULL,
  `ATEF_CABEZA` text NOT NULL,
  `ATEF_VISUAL` text NOT NULL,
  `ATEF_CUELLO` text NOT NULL,
  `ATEF_TORAX` text NOT NULL,
  `ATEF_ABDOMEN` text NOT NULL,
  `ATEF_GENITOURINARIO` text NOT NULL,
  `ATEF_OSTEOMUSCULAR` text NOT NULL,
  `ATEF_PIELYFANERAZ` text NOT NULL,
  `ATEF_NEUROLOGICO` text NOT NULL,
  `AGEN_ID` int(11) NOT NULL,
  `ATEF_CREATEBY` int(11) NOT NULL,
  `ATEF_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ATEF_ID`),
  KEY `AGEN_ID` (`AGEN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='EXAMEN FISICO';

CREATE TABLE IF NOT EXISTS `TBL_ATNANTECEDENTESGINECOLOGICOS` (
  `ATAG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATAG_MENARGUIA` varchar(20) NOT NULL DEFAULT '0',
  `ATAG_CICLOS` varchar(20) NOT NULL DEFAULT '0',
  `ATAG_FUM` DATETIME NOT NULL DEFAULT '0000-00-00',
  `ATAG_GRAVIDA` varchar(2) NOT NULL DEFAULT '0',
  `ATAG_PARTOS` varchar(2) NOT NULL DEFAULT '0',
  `ATAG_ABORTO` varchar(2) NOT NULL DEFAULT '0',
  `ATAG_CESARIA` varchar(2) NOT NULL DEFAULT '0',
  `ATAG_LACTANDO` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAG_DISMINORREA` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAG_EPI` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAG_COMPANEROS` varchar(2) NOT NULL DEFAULT '<1',
  `ATAG_MASHIJOS` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAG_ENFESEXU` varchar(2) NOT NULL DEFAULT 'NO',
  `ATAG_OTROS` text NOT NULL,
  `PERS_ID` int(11) NOT NULL,
  `ATAG_CREATEBY` int(11) NOT NULL,
  `ATAG_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ATAG_ID`),
  KEY `PERS_ID` (`PERS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ANTECEDENTES GINECOLOGICOS';

CREATE TABLE IF NOT EXISTS `TBL_ATNPLAN` (
  `ATPL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATPL_DESCRIPCION` text NOT NULL,
  `ATPL_OBSERVACIONES` text NOT NULL,
  `AGEN_ID` int(11) NOT NULL,
  `ATPL_CREATEBY` int(11) NOT NULL,
  `ATPL_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ATPL_ID`),
  KEY `AGEN_ID` (`AGEN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='PLAN';

CREATE TABLE IF NOT EXISTS `TBL_ATNTESTFINDRISK` (
  `ATTF_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATTF_EDAD` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_EDADPNTS` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_PESO` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_TALLA` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_IMC` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_IMCTOTAL` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_IMCPNTS` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_PC` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_PCMUJERES` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_PCPNTS` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_ACTIVIDADFISICA` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_ACTIVIDADFISICAPNTS` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_CONSUMEVERDURAS` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_CONSUMEVERDURASPNTS` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_TOMAMEDICAMENTOS` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_TOMAMEDICAMENTOSPNTS` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_GLUCOSA` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_GLUCOSAPNTS` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_DIABETESPARIENTES` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_DIABETESPARIENTESPNTS` varchar(45) NOT NULL DEFAULT '0',
  `ATTF_TOTALPNTS` varchar(45) NOT NULL DEFAULT '0',
  `AGEN_ID` int(11) NOT NULL,
  `ATTF_CREATEBY` int(11) NOT NULL,
  `ATTF_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ATTF_ID`),
  KEY `AGEN_ID` (`AGEN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='TEST DE FINDRISK';



CREATE TABLE IF NOT EXISTS `TBL_ATNDIAGNOSTICOS` (
  `ATDI_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATDI_RIESGOVICTIMA` varchar(5) DEFAULT 'NO',
  `ATDI_RIESGOVICTIMAVIO` varchar(5) DEFAULT 'NO',
  `DIAG_ID` int(11) NOT NULL,
  `CLDI_ID` int(11) NOT NULL,
  `TIDI_ID` int(11) NOT NULL,
  `AGEN_ID` int(11) NOT NULL,
  `ATDI_CREATEBY` int(11) NOT NULL,
  `ATDI_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ATDI_ID`),
  KEY `AGEN_ID` (`AGEN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='DIAGNOTICOS';

CREATE TABLE  `TBL_CLASESDIAGNOSTICOS` (
  `CLDI_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CLDI_NOMBRE` varchar(50) COLLATE utf8_spanish_ci NOT NULL,
  `CLDI_CREATEBY` int(11) NOT NULL,
  `CLDI_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CLDI_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='CLASES DIAGNOTICOS';

CREATE TABLE  `TBL_TIPOSDIAGNOSTICOS` (
  `TIDI_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TIDI_NOMBRE` varchar(50) COLLATE utf8_spanish_ci NOT NULL,
  `TIDI_CREATEBY` int(11) NOT NULL,
  `TIDI_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`TIDI_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='TIPOS DIAGNOTICOS';

CREATE TABLE  `TBL_DIAGNOSTICOS` (
  `DIAG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DIAG_NOMBRE` varchar(50) COLLATE utf8_spanish_ci NOT NULL,
  `DIAG_CODIGO` varchar(50) COLLATE utf8_spanish_ci NOT NULL,
  `DIAG_CREATEBY` int(11) NOT NULL,
  `DIAG_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`DIAG_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='DIAGNOTICOS';



CREATE TABLE IF NOT EXISTS `TBL_ATNRECETARIOS` (
  `ATRE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATRE_CANTIDAD` int(11) NOT NULL,
  `ATRE_TOMACADA` varchar(45) DEFAULT NULL,
  `ATRE_TOMACADADESCRIPCION` varchar(45) DEFAULT NULL,
  `ATRE_DURACION` varchar(45) DEFAULT NULL,
  `ATRE_DURACIONDESCRIPCION` varchar(45) DEFAULT NULL,
  `ATRE_DETALLES` varchar(45) DEFAULT NULL,
  `ATRE_VIASUMINISTRO` varchar(45) DEFAULT NULL,
  `ATRE_FECHAINICIO` date DEFAULT NULL,
  `ATRE_FORMULA` text NOT NULL,
  `MEDI_ID` int(11) NOT NULL,
  `AGEN_ID` int(11) NOT NULL,
  `ATRE_CREATEBY` int(11) NOT NULL,
  `ATRE_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ATRE_ID`),
  KEY `AGEN_ID` (`AGEN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='RECETARIOS';

CREATE TABLE IF NOT EXISTS `TBL_MEDICAMENTOS` (
  `MEDI_ID` int(11) NOT NULL AUTO_INCREMENT,
  `MEDI_CODIGOATC` varchar(20) NOT NULL,
  `MEDI_DESCRIPCIONATC` varchar(50) NOT NULL,
  `MEDI_PRINCIPIOACTIVO` varchar(50) NOT NULL,
  `MEDI_CONCENTRACION` varchar(50) DEFAULT NULL,
  `MEDI_FORMAFARMACEUTICA` text NOT NULL,
  `MEDI_ACLARACION` text,
  `MEDI_LISTA` varchar(2) NOT NULL,
  `MEDI_VALOR` varchar(45) DEFAULT NULL,
  `MEDI_CREATEBY` int(11) NOT NULL,
  `MEDI_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`MEDI_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='MEDICAMENTOS';


CREATE TABLE IF NOT EXISTS `TBL_ATNREMISIONES` (
  `ATRM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATRM_REMITIDOA` text NOT NULL,
  `ATRM_OBSERVACIONES` text NOT NULL,
  `AGEN_ID` int(11) NOT NULL, 
  `ATRM_CREATEBY` int(11) NOT NULL,
  `ATRM_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ATRM_ID`),
  KEY `AGEN_ID` (`AGEN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='REMISIONES';


CREATE TABLE  `TBL_TIPOSPROCEDIMIENTOS` (
  `TIPR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TIPR_NOMBRE` varchar(50) COLLATE utf8_spanish_ci NOT NULL,
  `TIPR_CREATEBY` int(11) NOT NULL,
  `TIPR_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`TIPR_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='TIPOS DE PROCEDIMIENTOS';

CREATE TABLE IF NOT EXISTS `TBL_PROCEDIMIENTOS` (
  `PROC_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROC_NOMBRE` text NOT NULL,
  `PROC_DESCRIPCION` text NULL,
  `PROC_CUPS` varchar(20) DEFAULT NULL,
  `PROC_SOAT` varchar(20) DEFAULT NULL,
  `PROC_VALOR` int(11) DEFAULT NULL,
  `PROC_REFERENCIA` text,
  `PROC_UNIDAD` varchar(45) NULL,
  `TIPR_ID` int(11) DEFAULT NULL,
  `ARLA_ID` int(11) NULL,
  `NILA_ID` int(11) NULL,
  `PROC_CREATEBY` int(11) NOT NULL,
  `PROC_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PROC_ID`),
  KEY `TIPR_ID` (`TIPR_ID`),
  KEY `ARLA_ID` (`ARLA_ID`),
  KEY `NILA_ID` (`NILA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='PROCEDIMIENTOS';


CREATE TABLE  TBL_ATNPROCEDIMIENTOS (
  `ATPR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATPR_OBSERVACIONES` text COLLATE utf8_spanish_ci,
  `ATPR_CANTIDAD` int(11) DEFAULT NULL,
  `ATPR_FECHASOLICITUD` date NOT NULL,
  `ATPR_RESULTADOS` text COLLATE utf8_spanish_ci,
  `ATPR_FECHAPROCESO` date DEFAULT NULL,
  `ATPR_ESTADO` tinyint(1) NOT NULL,
  `PROC_ID` int(11) NOT NULL,
  `AGEN_ID` int(11) NOT NULL,
  `ATPR_CREATEBY` int(11) NOT NULL,
  `ATPR_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ATPR_ID`),
  KEY `AGEN_ID` (`AGEN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='ATENCION PROCEDIMIENTOS';



CREATE TABLE  `TBL_TIPOPLAN` (
  `TIPL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TIPL_NOMBRE` varchar(50) NOT NULL,
  `TIPL_CREATEBY` int(11) NOT NULL,
  `TIPL_UPDATEAT` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`TIPL_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


CREATE TABLE  `TBL_MODALIDADPLAN` (
  `MOPL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `MOPL_NOMBRE` varchar(50) NOT NULL,
  `MOPL_CREATEBY` int(11) NOT NULL,
  `MOPL_UPDATEAT` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`MOPL_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

ALTER TABLE TBL_PLANES CHANGE COLUMN `PLAN_VALORMENSUAL` `PLAN_VALOR` DOUBLE DEFAULT NULL,
 DROP COLUMN `PLAN_VALORSEMESTRAL`, DROP COLUMN `PLAN_VALORANUAL`;

ALTER TABLE TBL_PLANES ADD COLUMN `MOPL_ID` INTEGER AFTER `PLAN_VALOR`;
ALTER TABLE TBL_PLANES ADD COLUMN `TIPL_ID` INTEGER AFTER `MOPL_ID`;


ALTER TABLE `DB_HOMECARE`.`TBL_AFILIADOS` DROP COLUMN `MEPA_ID`;
ALTER TABLE TBL_PAGOS ADD COLUMN `MEPA_ID` INTEGER NOT NULL AFTER `AFIL_ID`;
ALTER TABLE TBL_PAGOS ADD COLUMN `PAGO_SOPORTE` TEXT NULL AFTER `MEPA_ID`;
ALTER TABLE TBL_AFILIADOS ADD COLUMN `TIPL_ID` INTEGER NOT NULL AFTER `PERS_ID`;

ALTER TABLE TBL_AFILIADOS ADD COLUMN `AFIL_PERSONACONTACTO` varchar(100) NULL AFTER `ESAF_ID`;
ALTER TABLE TBL_AFILIADOS ADD COLUMN `AFIL_PARENTESCOPERSONACONTACTO` varchar(100) NULL AFTER `AFIL_PERSONACONTACTO`;
ALTER TABLE TBL_AFILIADOS ADD COLUMN `AFIL_MOVILPERSONACONTACTO` varchar(100) NULL AFTER `AFIL_PARENTESCOPERSONACONTACTO`;
ALTER TABLE TBL_AFILIADOS ADD COLUMN `AFIL_FIJOPERSONACONTACTO` varchar(100) NULL AFTER `AFIL_MOVILPERSONACONTACTO`;
ALTER TABLE TBL_AFILIADOS ADD COLUMN `AFIL_ASESOR` varchar(100) NULL AFTER `AFIL_FIJOPERSONACONTACTO`;


CREATE TABLE  `TBL_ATNRECOMENDACIONES` (
  `ATRE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATRE_RECOMENDACIONES` text COLLATE utf32_spanish_ci,
  `AGEN_ID` int(11) NOT NULL COMMENT 'AGENDA',
  `ATRE_CREATEBY` int(11) NOT NULL,
  `ATRE_UPDATEAT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ATRE_ID`),
  KEY `AGEN_ID` (`AGEN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf32 COLLATE=utf32_spanish_ci COMMENT='RECOMENDACIONES';
