DROP TRIGGER IF EXISTS DISP_INSERTARAGENDA;
DELIMITER //
CREATE TRIGGER DISP_INSERTARAGENDA AFTER INSERT ON TBL_AGENDA
 FOR EACH ROW BEGIN

  SET @ID= (SELECT MAX(AGEN_ID) FROM TBL_AGENDA);
  SET @TGN= (SELECT p.TIGE_ID FROM TBL_PERSONAS p INNER JOIN TBL_AGENDA a ON a.PERS_ID = p.PERS_ID WHERE a.AGEN_ID = NEW.AGEN_ID);
  
  SET @PANTP= (SELECT COUNT(t.PERS_ID) FROM TBL_ATNANTECEDENTESPERSONALES t WHERE t.PERS_ID = NEW.PERS_ID);
  SET @PANTF= (SELECT COUNT(t.PERS_ID) FROM TBL_ATNANTECEDENTESFAMILIARES t WHERE t.PERS_ID = NEW.PERS_ID);
  SET @PHBT= (SELECT COUNT(t.PERS_ID) FROM TBL_ATNHABITOS t WHERE t.PERS_ID = NEW.PERS_ID);
  SET @PANTG= (SELECT COUNT(t.PERS_ID) FROM TBL_ATNANTECEDENTESGINECOLOGICOS t WHERE t.PERS_ID = NEW.PERS_ID);

	CASE NEW.FINA_ID
	WHEN '1' THEN /*primera vez - medicina general*/
      
	  IF @PANTP=0 THEN
		INSERT INTO TBL_ATNANTECEDENTESPERSONALES SET ATAP_OTROS = 'Sin datos', PERS_ID=NEW.PERS_ID, ATAP_CREATEBY=NEW.AGEN_CREATEBY;	  
	  END IF;
	  
	  IF @PANTF=0 THEN	  
		INSERT INTO TBL_ATNANTECEDENTESFAMILIARES SET ATAF_OTROS = 'Sin datos', PERS_ID=NEW.PERS_ID, ATAF_CREATEBY=NEW.AGEN_CREATEBY;
	  END IF;
	  
	  IF @PHBT=0 THEN	  
		INSERT INTO TBL_ATNHABITOS SET ATHA_OTROS="Sin datos", PERS_ID=NEW.PERS_ID, ATHA_CREATEBY=NEW.AGEN_CREATEBY;
	  END IF;
	  

      IF @TGN=2 THEN
		IF @PANTG=0 THEN
		   INSERT INTO TBL_ATNANTECEDENTESGINECOLOGICOS SET ATAG_MENARGUIA="Sin datos", ATAG_CICLOS="Sin datos", ATAG_FUM=NEW.AGEN_FECHA, ATAG_OTROS="Sin datos", PERS_ID=NEW.PERS_ID, ATAG_CREATEBY=NEW.AGEN_CREATEBY;
		END IF;
	  END IF;

      INSERT INTO TBL_ATNGENERALIDADES SET CAEX_ID = 15, AGEN_ID=@ID, ATGE_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNTESTFINDRISK SET AGEN_ID=@ID, ATTF_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNREVISIONSISTEMAS SET ATRS_GENERAL="NORMAL", ATRS_RESPIRATORIO="NORMAL", ATRS_CARDIOVASCULAR="NORMAL", ATRS_GASTROINTESTINAL="NORMAL", ATRS_GENITOURINARIO="NORMAL", ATRS_ENDOCRINO="NORMAL", ATRS_NEUROLOGICO="NORMAL",   AGEN_ID=@ID, ATRS_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNSIGNOSVITALES SET AGEN_ID=@ID, ATSV_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNEXAMENFISICO SET ATEF_ASPECTO="NORMAL", ATEF_ESTADO="NORMAL", ATEF_CABEZA="NORMAL", ATEF_VISUAL="NORMAL", ATEF_CUELLO="NORMAL", ATEF_TORAX="NORMAL", ATEF_ABDOMEN="NORMAL", ATEF_GENITOURINARIO="NORMAL", ATEF_OSTEOMUSCULAR="NORMAL", ATEF_PIELYFANERAZ="NORMAL", ATEF_NEUROLOGICO="NORMAL", AGEN_ID=@ID, ATEF_CREATEBY=NEW.AGEN_CREATEBY;
	  INSERT INTO TBL_ATNPLAN SET ATPL_DESCRIPCION='Sin datos', ATPL_OBSERVACIONES='Sin datos', AGEN_ID=@ID, ATPL_CREATEBY=NEW.AGEN_CREATEBY;
    
	WHEN '4' THEN /*primera vez - riesgo cardiovascular*/
      
	  IF @PANTP=0 THEN
		INSERT INTO TBL_ATNANTECEDENTESPERSONALES SET ATAP_OTROS = 'Sin datos', PERS_ID=NEW.PERS_ID, ATAP_CREATEBY=NEW.AGEN_CREATEBY;	  
	  END IF;
	  
	  IF @PANTF=0 THEN	  
		INSERT INTO TBL_ATNANTECEDENTESFAMILIARES SET ATAF_OTROS = 'Sin datos', PERS_ID=NEW.PERS_ID, ATAF_CREATEBY=NEW.AGEN_CREATEBY;
	  END IF;
	  
	  IF @PHBT=0 THEN	  
		INSERT INTO TBL_ATNHABITOS SET ATHA_OTROS="Sin datos", PERS_ID=NEW.PERS_ID, ATHA_CREATEBY=NEW.AGEN_CREATEBY;
	  END IF;
	  

      IF @TGN=2 THEN
		IF @PANTG=0 THEN
		   INSERT INTO TBL_ATNANTECEDENTESGINECOLOGICOS SET ATAG_MENARGUIA="Sin datos", ATAG_CICLOS="Sin datos", ATAG_FUM=NEW.AGEN_FECHA, ATAG_OTROS="Sin datos", PERS_ID=NEW.PERS_ID, ATAG_CREATEBY=NEW.AGEN_CREATEBY;
		END IF;
	  END IF;

      INSERT INTO TBL_ATNGENERALIDADES SET CAEX_ID = 15, AGEN_ID=@ID, ATGE_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNTESTFINDRISK SET AGEN_ID=@ID, ATTF_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNREVISIONSISTEMAS SET ATRS_GENERAL="NORMAL", ATRS_RESPIRATORIO="NORMAL", ATRS_CARDIOVASCULAR="NORMAL", ATRS_GASTROINTESTINAL="NORMAL", ATRS_GENITOURINARIO="NORMAL", ATRS_ENDOCRINO="NORMAL", ATRS_NEUROLOGICO="NORMAL",   AGEN_ID=@ID, ATRS_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNSIGNOSVITALES SET AGEN_ID=@ID, ATSV_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNEXAMENFISICO SET ATEF_ASPECTO="NORMAL", ATEF_ESTADO="NORMAL", ATEF_CABEZA="NORMAL", ATEF_VISUAL="NORMAL", ATEF_CUELLO="NORMAL", ATEF_TORAX="NORMAL", ATEF_ABDOMEN="NORMAL", ATEF_GENITOURINARIO="NORMAL", ATEF_OSTEOMUSCULAR="NORMAL", ATEF_PIELYFANERAZ="NORMAL", ATEF_NEUROLOGICO="NORMAL", AGEN_ID=@ID, ATEF_CREATEBY=NEW.AGEN_CREATEBY;
	  INSERT INTO TBL_ATNPLAN SET ATPL_DESCRIPCION='Sin datos', ATPL_OBSERVACIONES='Sin datos', AGEN_ID=@ID, ATPL_CREATEBY=NEW.AGEN_CREATEBY;
	
	WHEN '5' THEN /*control - riesgo cardiovascular*/
	  INSERT INTO TBL_ATNGENERALIDADES SET CAEX_ID = 15, AGEN_ID=@ID, ATGE_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNTESTFINDRISK SET AGEN_ID=@ID, ATTF_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNREVISIONSISTEMAS SET ATRS_GENERAL="NORMAL", ATRS_RESPIRATORIO="NORMAL", ATRS_CARDIOVASCULAR="NORMAL", ATRS_GASTROINTESTINAL="NORMAL", ATRS_GENITOURINARIO="NORMAL", ATRS_ENDOCRINO="NORMAL", ATRS_NEUROLOGICO="NORMAL",   AGEN_ID=@ID, ATRS_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNSIGNOSVITALES SET AGEN_ID=@ID, ATSV_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNEXAMENFISICO SET ATEF_ASPECTO="NORMAL", ATEF_ESTADO="NORMAL", ATEF_CABEZA="NORMAL", ATEF_VISUAL="NORMAL", ATEF_CUELLO="NORMAL", ATEF_TORAX="NORMAL", ATEF_ABDOMEN="NORMAL", ATEF_GENITOURINARIO="NORMAL", ATEF_OSTEOMUSCULAR="NORMAL", ATEF_PIELYFANERAZ="NORMAL", ATEF_NEUROLOGICO="NORMAL", AGEN_ID=@ID, ATEF_CREATEBY=NEW.AGEN_CREATEBY;
	  INSERT INTO TBL_ATNPLAN SET ATPL_DESCRIPCION='Sin datos', ATPL_OBSERVACIONES='Sin datos', AGEN_ID=@ID, ATPL_CREATEBY=NEW.AGEN_CREATEBY;
	
	WHEN '3' THEN /*control - medicina general*/
	  INSERT INTO TBL_ATNGENERALIDADES SET CAEX_ID = 15, AGEN_ID=@ID, ATGE_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNTESTFINDRISK SET AGEN_ID=@ID, ATTF_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNREVISIONSISTEMAS SET ATRS_GENERAL="NORMAL", ATRS_RESPIRATORIO="NORMAL", ATRS_CARDIOVASCULAR="NORMAL", ATRS_GASTROINTESTINAL="NORMAL", ATRS_GENITOURINARIO="NORMAL", ATRS_ENDOCRINO="NORMAL", ATRS_NEUROLOGICO="NORMAL",   AGEN_ID=@ID, ATRS_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNSIGNOSVITALES SET AGEN_ID=@ID, ATSV_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNEXAMENFISICO SET ATEF_ASPECTO="NORMAL", ATEF_ESTADO="NORMAL", ATEF_CABEZA="NORMAL", ATEF_VISUAL="NORMAL", ATEF_CUELLO="NORMAL", ATEF_TORAX="NORMAL", ATEF_ABDOMEN="NORMAL", ATEF_GENITOURINARIO="NORMAL", ATEF_OSTEOMUSCULAR="NORMAL", ATEF_PIELYFANERAZ="NORMAL", ATEF_NEUROLOGICO="NORMAL", AGEN_ID=@ID, ATEF_CREATEBY=NEW.AGEN_CREATEBY;
	  INSERT INTO TBL_ATNPLAN SET ATPL_DESCRIPCION='Sin datos', ATPL_OBSERVACIONES='Sin datos', AGEN_ID=@ID, ATPL_CREATEBY=NEW.AGEN_CREATEBY;
	
	WHEN '6' THEN /*primera vez - pediatria*/
      
	  IF @PANTP=0 THEN
		INSERT INTO TBL_ATNANTECEDENTESPERSONALES SET ATAP_OTROS = 'Sin datos', PERS_ID=NEW.PERS_ID, ATAP_CREATEBY=NEW.AGEN_CREATEBY;	  
	  END IF;
	  
	  IF @PANTF=0 THEN	  
		INSERT INTO TBL_ATNANTECEDENTESFAMILIARES SET ATAF_OTROS = 'Sin datos', PERS_ID=NEW.PERS_ID, ATAF_CREATEBY=NEW.AGEN_CREATEBY;
	  END IF;
	  
	  IF @PHBT=0 THEN	  
		INSERT INTO TBL_ATNHABITOS SET ATHA_OTROS="Sin datos", PERS_ID=NEW.PERS_ID, ATHA_CREATEBY=NEW.AGEN_CREATEBY;
	  END IF;
	  

      IF @TGN=2 THEN
		IF @PANTG=0 THEN
		   INSERT INTO TBL_ATNANTECEDENTESGINECOLOGICOS SET ATAG_MENARGUIA="Sin datos", ATAG_CICLOS="Sin datos", ATAG_FUM=NEW.AGEN_FECHA, ATAG_OTROS="Sin datos", PERS_ID=NEW.PERS_ID, ATAG_CREATEBY=NEW.AGEN_CREATEBY;
		END IF;
	  END IF;

      INSERT INTO TBL_ATNGENERALIDADES SET CAEX_ID = 15, AGEN_ID=@ID, ATGE_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNTESTFINDRISK SET AGEN_ID=@ID, ATTF_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNREVISIONSISTEMAS SET ATRS_GENERAL="NORMAL", ATRS_RESPIRATORIO="NORMAL", ATRS_CARDIOVASCULAR="NORMAL", ATRS_GASTROINTESTINAL="NORMAL", ATRS_GENITOURINARIO="NORMAL", ATRS_ENDOCRINO="NORMAL", ATRS_NEUROLOGICO="NORMAL",   AGEN_ID=@ID, ATRS_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNSIGNOSVITALES SET AGEN_ID=@ID, ATSV_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNEXAMENFISICO SET ATEF_ASPECTO="NORMAL", ATEF_ESTADO="NORMAL", ATEF_CABEZA="NORMAL", ATEF_VISUAL="NORMAL", ATEF_CUELLO="NORMAL", ATEF_TORAX="NORMAL", ATEF_ABDOMEN="NORMAL", ATEF_GENITOURINARIO="NORMAL", ATEF_OSTEOMUSCULAR="NORMAL", ATEF_PIELYFANERAZ="NORMAL", ATEF_NEUROLOGICO="NORMAL", AGEN_ID=@ID, ATEF_CREATEBY=NEW.AGEN_CREATEBY;
	  INSERT INTO TBL_ATNPLAN SET ATPL_DESCRIPCION='Sin datos', ATPL_OBSERVACIONES='Sin datos', AGEN_ID=@ID, ATPL_CREATEBY=NEW.AGEN_CREATEBY;
    
	WHEN '7' THEN /*control -pediatria*/
	  INSERT INTO TBL_ATNGENERALIDADES SET CAEX_ID = 15, AGEN_ID=@ID, ATGE_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNTESTFINDRISK SET AGEN_ID=@ID, ATTF_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNREVISIONSISTEMAS SET ATRS_GENERAL="NORMAL", ATRS_RESPIRATORIO="NORMAL", ATRS_CARDIOVASCULAR="NORMAL", ATRS_GASTROINTESTINAL="NORMAL", ATRS_GENITOURINARIO="NORMAL", ATRS_ENDOCRINO="NORMAL", ATRS_NEUROLOGICO="NORMAL",   AGEN_ID=@ID, ATRS_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNSIGNOSVITALES SET AGEN_ID=@ID, ATSV_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNEXAMENFISICO SET ATEF_ASPECTO="NORMAL", ATEF_ESTADO="NORMAL", ATEF_CABEZA="NORMAL", ATEF_VISUAL="NORMAL", ATEF_CUELLO="NORMAL", ATEF_TORAX="NORMAL", ATEF_ABDOMEN="NORMAL", ATEF_GENITOURINARIO="NORMAL", ATEF_OSTEOMUSCULAR="NORMAL", ATEF_PIELYFANERAZ="NORMAL", ATEF_NEUROLOGICO="NORMAL", AGEN_ID=@ID, ATEF_CREATEBY=NEW.AGEN_CREATEBY;
	  INSERT INTO TBL_ATNPLAN SET ATPL_DESCRIPCION='Sin datos', ATPL_OBSERVACIONES='Sin datos', AGEN_ID=@ID, ATPL_CREATEBY=NEW.AGEN_CREATEBY;
	
	
	WHEN '11' THEN /*primera vez - consulta medica domiciliaria*/
      
	  IF @PANTP=0 THEN
		INSERT INTO TBL_ATNANTECEDENTESPERSONALES SET ATAP_OTROS = 'Sin datos', PERS_ID=NEW.PERS_ID, ATAP_CREATEBY=NEW.AGEN_CREATEBY;	  
	  END IF;
	  
	  IF @PANTF=0 THEN	  
		INSERT INTO TBL_ATNANTECEDENTESFAMILIARES SET ATAF_OTROS = 'Sin datos', PERS_ID=NEW.PERS_ID, ATAF_CREATEBY=NEW.AGEN_CREATEBY;
	  END IF;
	  
	  IF @PHBT=0 THEN	  
		INSERT INTO TBL_ATNHABITOS SET ATHA_OTROS="Sin datos", PERS_ID=NEW.PERS_ID, ATHA_CREATEBY=NEW.AGEN_CREATEBY;
	  END IF;
	  

      IF @TGN=2 THEN
		IF @PANTG=0 THEN
		   INSERT INTO TBL_ATNANTECEDENTESGINECOLOGICOS SET ATAG_MENARGUIA="Sin datos", ATAG_CICLOS="Sin datos", ATAG_FUM=NEW.AGEN_FECHA, ATAG_OTROS="Sin datos", PERS_ID=NEW.PERS_ID, ATAG_CREATEBY=NEW.AGEN_CREATEBY;
		END IF;
	  END IF;

      INSERT INTO TBL_ATNGENERALIDADES SET CAEX_ID = 15, AGEN_ID=@ID, ATGE_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNTESTFINDRISK SET AGEN_ID=@ID, ATTF_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNREVISIONSISTEMAS SET ATRS_GENERAL="NORMAL", ATRS_RESPIRATORIO="NORMAL", ATRS_CARDIOVASCULAR="NORMAL", ATRS_GASTROINTESTINAL="NORMAL", ATRS_GENITOURINARIO="NORMAL", ATRS_ENDOCRINO="NORMAL", ATRS_NEUROLOGICO="NORMAL",   AGEN_ID=@ID, ATRS_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNSIGNOSVITALES SET AGEN_ID=@ID, ATSV_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNEXAMENFISICO SET ATEF_ASPECTO="NORMAL", ATEF_ESTADO="NORMAL", ATEF_CABEZA="NORMAL", ATEF_VISUAL="NORMAL", ATEF_CUELLO="NORMAL", ATEF_TORAX="NORMAL", ATEF_ABDOMEN="NORMAL", ATEF_GENITOURINARIO="NORMAL", ATEF_OSTEOMUSCULAR="NORMAL", ATEF_PIELYFANERAZ="NORMAL", ATEF_NEUROLOGICO="NORMAL", AGEN_ID=@ID, ATEF_CREATEBY=NEW.AGEN_CREATEBY;
	  INSERT INTO TBL_ATNPLAN SET ATPL_DESCRIPCION='Sin datos', ATPL_OBSERVACIONES='Sin datos', AGEN_ID=@ID, ATPL_CREATEBY=NEW.AGEN_CREATEBY;
    
	WHEN '12' THEN /*control - consulta medica domiciliaria*/
	  INSERT INTO TBL_ATNGENERALIDADES SET CAEX_ID = 15, AGEN_ID=@ID, ATGE_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNTESTFINDRISK SET AGEN_ID=@ID, ATTF_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNREVISIONSISTEMAS SET ATRS_GENERAL="NORMAL", ATRS_RESPIRATORIO="NORMAL", ATRS_CARDIOVASCULAR="NORMAL", ATRS_GASTROINTESTINAL="NORMAL", ATRS_GENITOURINARIO="NORMAL", ATRS_ENDOCRINO="NORMAL", ATRS_NEUROLOGICO="NORMAL",   AGEN_ID=@ID, ATRS_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNSIGNOSVITALES SET AGEN_ID=@ID, ATSV_CREATEBY=NEW.AGEN_CREATEBY;
      INSERT INTO TBL_ATNEXAMENFISICO SET ATEF_ASPECTO="NORMAL", ATEF_ESTADO="NORMAL", ATEF_CABEZA="NORMAL", ATEF_VISUAL="NORMAL", ATEF_CUELLO="NORMAL", ATEF_TORAX="NORMAL", ATEF_ABDOMEN="NORMAL", ATEF_GENITOURINARIO="NORMAL", ATEF_OSTEOMUSCULAR="NORMAL", ATEF_PIELYFANERAZ="NORMAL", ATEF_NEUROLOGICO="NORMAL", AGEN_ID=@ID, ATEF_CREATEBY=NEW.AGEN_CREATEBY;
	  INSERT INTO TBL_ATNPLAN SET ATPL_DESCRIPCION='Sin datos', ATPL_OBSERVACIONES='Sin datos', AGEN_ID=@ID, ATPL_CREATEBY=NEW.AGEN_CREATEBY;
	
	WHEN '14' THEN /*primera vez - asistencia medica telefonica*/
	  INSERT INTO TBL_ATNGENERALIDADES SET CAEX_ID = 15, AGEN_ID=@ID, ATGE_CREATEBY=NEW.AGEN_CREATEBY;
	  INSERT INTO TBL_ATNRECOMENDACIONES SET AGEN_ID=@ID, ATRE_CREATEBY=NEW.AGEN_CREATEBY;
	  
	WHEN '15' THEN /*control - asistencia medica telefonica*/
	  INSERT INTO TBL_ATNGENERALIDADES SET CAEX_ID = 15, AGEN_ID=@ID, ATGE_CREATEBY=NEW.AGEN_CREATEBY;
	  INSERT INTO TBL_ATNRECOMENDACIONES SET AGEN_ID=@ID, ATRE_CREATEBY=NEW.AGEN_CREATEBY;
      
	
  ELSE SET @ID = '0';
 	END CASE;

END
//
DELIMITER ;

DROP TRIGGER IF EXISTS `DISP_CLEARAGENDA`;
DELIMITER $$
CREATE TRIGGER `DISP_CLEARAGENDA` AFTER DELETE ON `TBL_AGENDA`
FOR EACH ROW BEGIN

DELETE FROM TBL_ATNEXAMENFISICO WHERE TBL_ATNEXAMENFISICO.AGEN_ID = OLD.AGEN_ID;
DELETE FROM TBL_ATNDIAGNOSTICOS WHERE TBL_ATNDIAGNOSTICOS.AGEN_ID = OLD.AGEN_ID;
DELETE FROM TBL_ATNGENERALIDADES WHERE TBL_ATNGENERALIDADES.AGEN_ID = OLD.AGEN_ID;
DELETE FROM TBL_ATNRECOMENDACIONES WHERE TBL_ATNRECOMENDACIONES.AGEN_ID = OLD.AGEN_ID;
DELETE FROM TBL_ATNPLAN WHERE TBL_ATNPLAN.AGEN_ID = OLD.AGEN_ID;
DELETE FROM TBL_ATNPROCEDIMIENTOS WHERE TBL_ATNPROCEDIMIENTOS.AGEN_ID = OLD.AGEN_ID;
DELETE FROM TBL_ATNRECETARIOS WHERE TBL_ATNRECETARIOS.AGEN_ID = OLD.AGEN_ID;
DELETE FROM TBL_ATNREMISIONES WHERE TBL_ATNREMISIONES.AGEN_ID = OLD.AGEN_ID;
DELETE FROM TBL_ATNREVISIONSISTEMAS WHERE TBL_ATNREVISIONSISTEMAS.AGEN_ID = OLD.AGEN_ID;
DELETE FROM TBL_ATNSIGNOSVITALES WHERE TBL_ATNSIGNOSVITALES.AGEN_ID = OLD.AGEN_ID;
DELETE FROM TBL_ATNTESTFINDRISK WHERE TBL_ATNTESTFINDRISK.AGEN_ID = OLD.AGEN_ID;

END $$
DELIMITER ;
